### ISSUE TITLE
Fatal error: Uncaught BadMethodCallException

### ISSUE THREAD

**Issue by ookris** [vaughany/yourls-popular-clicks-extended#12]
**Describe the bug**
I get this error after updating YOURLS to the latest one.

`Fatal error: Uncaught BadMethodCallException: Class 'YOURLS\Database\YDB' does not have a method 'get_results' in /public_html/out/includes/vendor/aura/sql/src/AbstractExtendedPdo.php:113 Stack trace: #10 
/public_html/out/user/plugins/yourls-popular-clicks-extended/plugin.php(161): Aura\Sql\AbstractExtendedPdo->__call('get_results', Array) #1 /public_html/out/user/plugins/yourls-popular-clicks-extended/plugin.php(248): vaughany_show_specific_period('2022-04-29 18', 'hour', 20, 'this hour (29th...') #2 /public_html/out/includes/functions-plugins.php(819): vaughany_popularclicksextended_display_page() #3 /public_html/out/admin/plugins.php(8): yourls_plugin_admin_page('popularclicksex...') #4 {main} thrown in /public_html/out/includes/vendor/aura/sql/src/AbstractExtendedPdo.php on line 113`

The error shows up in the plug-in menu.

**Comment by ookris** [comment]
Problem has been solved.
It is enough to change the value in the plugin code:
`get_results`
on
`fetchObjects`
in lines: 88, 161, 219
